# -*- coding: utf-8 -*-
"""NM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvDZeDU5befDEzsR_2UvioPWKgmjvYen

TASK - 1
"""

# Task 1: Define restaurant information

restaurant_info = {
    "name": "Tasty Bites",
    "total_tables": 10,
    "seats_per_table": 4,
    "time_slots": ["18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30"],
    "max_party_size": 6,
    "reservation_cutoff_minutes": 60
}

# Show the collected information
for key, value in restaurant_info.items():
    print(f"{key}: {value}")

"""TASK - 2"""

import json

# Data to store in JSON file (a reservation example)
reservation_data = [
    {
        "customer_name": "Alice",
        "party_size": 3,
        "reservation_time": "19:00",
        "table_number": 2,
        "contact": "alice@example.com"
    }
]

# Create and write data to reservations.json file
with open('reservations.json', 'w') as file:
    json.dump(reservation_data, file, indent=4)

# Confirm that the file was created
print("JSON file 'reservations.json' created!")

# Read the contents of the JSON file
with open('reservations.json', 'r') as file:
    data = json.load(file)
    print(json.dumps(data, indent=4))

new_reservation = {
    "customer_name": "Bob",
    "party_size": 4,
    "reservation_time": "20:00",
    "table_number": 5,
    "contact": "bob@example.com"
}

# Load existing reservations from the JSON file
with open('reservations.json', 'r') as file:
    data = json.load(file)

# Add the new reservation to the list
data.append(new_reservation)

# Save the updated list back to the JSON file
with open('reservations.json', 'w') as file:
    json.dump(data, file, indent=4)

# Confirm the addition
print("New reservation added!")

